name: Setup typos
description: 'Cache and setup typos'

runs:
  using: 'composite'

  steps:
    - name: Cache cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ runner.os }}-cargo-typos-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-typos-
          ${{ runner.os }}-cargo-

    - name: Install typos
      shell: bash
      run: |
        if ! command -v typos &> /dev/null; then
          cargo install typos-cli
        else
          echo "typos is already installed, skipping installation"
        fi
        typos --version
