name: Setup typos
description: 'Cache and setup typos'

runs:
  using: 'composite'

  steps:
    - name: Install typos
      uses: baptiste0928/cargo-install@8195d4f734a149db85385bb4102b42efcd373759 # v3
      with:
        crate: typos-cli
        version: 1.36.2

    - name: Run typos
      shell: bash
      run: typos --version
