name: Setup typos
description: 'Cache and setup typos'

runs:
  using: 'composite'

  steps:
    - name: Install typos
      uses: baptiste0928/cargo-install@v3
      with:
        crate: typos-cli
        version: 1.36.2

    - name: Run typos
      shell: bash
      run: typos --version
