name: Setup typos
description: 'Cache and setup typos'

runs:
  using: 'composite'

  steps:
    - name: Install typos
      uses: baptiste0928/cargo-install@f204293d9709061b7bc1756fec3ec4e2cd57dec0 # v3
      with:
        crate: typos-cli
        version: 1.36.2

    - name: Run typos
      shell: bash
      run: typos --version
