name: rspec

on: [push]

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["3.3", "3.4"]

    steps:
      - uses: actions/checkout@v4
      - name: Install typos
        run: |
          wget https://github.com/crate-ci/typos/releases/download/v1.29.7/typos-v1.29.7-x86_64-unknown-linux-musl.tar.gz
          tar xf typos-v1.29.7-x86_64-unknown-linux-musl.tar.gz
          mkdir -p $HOME/.cargo/bin
          mv typos $HOME/.cargo/bin/
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          typos --version
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake
