name: rubocop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 4.0.6
          bundler-cache: true

      - name: Run rubocop
        run: bundle exec rubocop
